# Generated by Django 2.0.3 on 2019-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drawing',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('problemtext', models.TextField()),
                ('problemimg', models.FilePathField(path='F:\\program-example\\机械\\Myproject\\files/images/drawing_pratice')),
                ('answeretext', models.TextField()),
                ('answereimg', models.FilePathField(path='F:\\program-example\\机械\\Myproject\\files/images/drawing_pratice')),
                ('hasthreed', models.IntegerField(default=0)),
                ('keyword1', models.CharField(max_length=20)),
                ('keyword2', models.CharField(default='', max_length=20)),
                ('keyword3', models.CharField(default='', max_length=20)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fillblanks',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=200)),
                ('answere1', models.CharField(default='', max_length=100)),
                ('answere2', models.CharField(default='', max_length=100)),
                ('answere3', models.CharField(default='', max_length=100)),
                ('answere4', models.CharField(default='', max_length=100)),
                ('answere5', models.CharField(default='', max_length=100)),
                ('answere6', models.CharField(default='', max_length=100)),
                ('answere7', models.CharField(default='', max_length=100)),
                ('answere8', models.CharField(default='', max_length=100)),
                ('keyword1', models.CharField(max_length=20)),
                ('keyword2', models.CharField(default='', max_length=20)),
                ('keyword3', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
