# Generated by Django 2.0.3 on 2019-03-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='answereimg',
            field=models.FilePathField(path='F:/program-example/机械/Myproject/files/images/drawing_pratice'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='problemimg',
            field=models.FilePathField(path='F:/program-example/机械/Myproject/files/images/drawing_pratice'),
        ),
    ]
