# Generated by Django 2.0.3 on 2019-03-09 01:33

from django.db import migrations, models
import user_information.imagestorage


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='avatar',
            field=models.ImageField(default='images/avatar/default/originavatar.jpg', storage=user_information.imagestorage.ImageStorage(), upload_to='images/avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='flag',
            field=models.IntegerField(default=2),
        ),
    ]
